version: '3.8'

services:
  ai-dj-streamer:
    build: .
    ports:
      - "8002:8002"
    environment:
      - CONFLUENT_BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
      - CONFLUENT_API_KEY=${CONFLUENT_API_KEY}
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-live-chat}
    volumes:
      - ./kafka_config.py:/app/kafka_config.py:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 