services:
  - type: web
    name: ai-dj-streamer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: CONFLUENT_BOOTSTRAP_SERVERS
        value: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
      - key: CONFLUENT_API_KEY
        value: QFPRKE7R65LCROC2
      - key: CONFLUENT_API_SECRET
        value: 36Q8gjZhYTnwFlbENZqoa91BuHIyOipkHm/LjbFf8NFsF+IafYcgHuFY6VatZ9WQ
      - key: KAFKA_TOPIC
        value: live-chat
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
      - key: LOG_LEVEL
        value: INFO 